# configuration file for dotnet-releaser
# Disable default packs - It will only publish NuGet and the Changelog
[msbuild]
project = "XenoAtom.Graphics.sln"
[github]
user = "XenoAtom"
repo = "XenoAtom.Graphics"
[changelog]
publish = false
owners = ["xoofx"] # To avoid to be mentioned in the changelog
